name: Build and deploy Spring Boot app to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'document-generator-quejate'
  AZURE_WEBAPP_PACKAGE_PATH: 'target/*.jar'
  JAVA_VERSION: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        env:
          SPRING_AI_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure startup command
        run: |
          echo "JAVA_OPTS=-Dserver.port=80" >> $GITHUB_ENV
          echo "STARTUP_COMMAND=java -jar /home/site/wwwroot/$(ls *.jar | head -1)" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: '*.jar'
          start-up-command: ${{ env.STARTUP_COMMAND }}
          app-settings: |
            JAVA_OPTS=${{ env.JAVA_OPTS }}
